# Change these first
owner: LyoSU # Your GitHub organization or username, where this repository lives
repo: upptimly # The name of this repository

assignees: # Users to assign downtime issues (optional)
  - LyoSU

sites:
  - name: lyo.su
    url: https://lyo.su
  - name: quote-api
    method: POST
    url: https://bot.lyo.su/quote/generate
    expectedStatusCodes:
      - 400
      - 429
  - name: hetzner
    url: https://hz.lyo.su
  - name: mongo-hetzner
    check: "tcp-ping"
    url: $URI_HETZNER
    port: 27017
  - name: oracle
    check: "tcp-ping"
    url: $URI_ORACLE
    port: 22  

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  cname: status.lyo.su
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /upptimly
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime**"
  introMessage: ly uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
